### PR TITLE
PHP version upgrade to 7.4 and PHPUnit upgrade to ^9.0.

### PR DESCRIPTION
**Pull request by ales-k**
PHP 8 disables libxml_disable_entity_loader by default:
https://php.watch/versions/8.0/libxml_disable_entity_loader-deprecation

PHPUnit - changing method expectExceptionMessageRegExp() to expectExceptionMessageMatches():
https://github.com/sebastianbergmann/phpunit/issues/4133

---

I actually tested executing in PHP 8.0 and it worked. I also executed phpunit tests which (after my changes) passed. However I am new to contributing so I will be really glad for any feedback or advice how to make sure that my changes are correct and actually helpful.

### CODE REVIEW

**Comment by mougrim** [comment]
Hi!
Thanks for contribution!

As I see php7.4 is [supported yet](https://www.php.net/supported-versions.php).
So, please, provide minimum php version 7.4 in composer.json.

For libxml_disable_entity_loader you can use suggest form your link:
```diff
- libxml_disable_entity_loader(true);
+ if (\PHP_VERSION_ID < 80000) {
+      libxml_disable_entity_loader(true);
+ }
```
Please, fix it.

Also, could you fix .travis.yml? Need to remove old php version and add 7.4, 8.0, 8.1 (if supported by travis).

**Comment by mougrim** [comment]
Sorry, looks like travis doesn't work now, so, isn't need to change .travis.yml.

**Comment by ales-k** [comment]
Thanks for your fast reply! Changes done.

**Comment by mougrim** [comment]
Thanks!

php8.1 and php8.0 are ok.
On php7.4 got errors in tests:
```
ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE)

/vendor/psr/log/src/LoggerInterface.php:30
/vendor/monolog/monolog/src/Monolog/Logger.php:34
/tests/Unit/Xml/DomXmlConverterTest.php:405
/tests/Unit/Xml/DomXmlConverterTest.php:28
phpvfscomposer:///vendor/phpunit/phpunit/phpunit:97
```
Looks like need to update composer.lock.

Also, could you update CHANGELOG.md?

**Comment by mougrim** [comment]
Thanks! Will add composer.lock later with code-style fixes (after update cs tool).

**Comment by mougrim** [comment]
@ales-k, released v0.5.0

**Comment by ales-k** [comment]
Thank you very much for your help.

**Pull request merged**
